### ISSUE TITLE
Tests are failing for libvirtcontroller module

### ISSUE THREAD

**Issue by olivergs** [fleet-commander/fc-admin#248]
Tests are failing because the output from the libvirt library is returning the XML with the elements and parameters in a different order than the template we have.

We need to find a way to normalize the data before do the comparison

**Comment by stanislavlevin** [comment]
The root cause is Python3.8 in which
https://docs.python.org/3/library/xml.etree.elementtree.html#xml.etree.ElementTree.tostring

> Changed in version 3.8: The tostring() function now preserves the attribute order specified by the user.

I have the fix, which works:
1) don't directly read xml file, but delegate this task to xml module
2) apply custom sorting

**Comment by olivergs** [comment]
You mean you have it already coded or just the solution?
I can code it, just want to know so we do not do the work twice :)

**Comment by stanislavlevin** [comment]
I found the commit here :wink:

**Comment by olivergs** [comment]
Thanks. Please send it in a PR when you have time :)

Cheers

**Comment by stanislavlevin** [comment]
More details
```
FAIL: 04_libvirt_controller.py
...
DEBUG:root:libvirtcontroller: Already connected. Reusing connection.
/usr/lib64/python3.8/subprocess.py:942: ResourceWarning: subprocess 3086856 is still running
  _warn("subprocess %s is still running" % self.pid,
ResourceWarning: Enable tracemalloc to get the object allocation traceback
.
======================================================================
FAIL: test_05_start (__main__.TestLibVirtControllerSessionMode)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./04_libvirt_controller.py", line 237, in test_05_start
    self.assertEqual(new_domain.XMLDesc(), libvirtmock.XML_MODIF.strip() % {'name-uuid': new_domain.UUIDString()[:8], 'uuid': new_domain.UUIDString()})
AssertionError: '<dom[100 chars]1.0" type="kvm" id="4">\n  <name>fc-ceac44d6</[5983 chars]ain>' != '<dom[100 chars]1.0" id="4" type="kvm">\n  <name>fc-ceac44d6</[5983 chars]ain>'
Diff is 10344 characters long. Set self.maxDiff to None to see it.

======================================================================
FAIL: test_05_start (__main__.TestLibVirtControllerSystemMode)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./04_libvirt_controller.py", line 237, in test_05_start
    self.assertEqual(new_domain.XMLDesc(), libvirtmock.XML_MODIF.strip() % {'name-uuid': new_domain.UUIDString()[:8], 'uuid': new_domain.UUIDString()})
AssertionError: '<dom[100 chars]1.0" type="kvm" id="4">\n  <name>fc-d99e7dbd</[5983 chars]ain>' != '<dom[100 chars]1.0" id="4" type="kvm">\n  <name>fc-d99e7dbd</[5983 chars]ain>'
Diff is 10344 characters long. Set self.maxDiff to None to see it.

----------------------------------------------------------------------
Ran 14 tests in 0.308s

FAILED (failures=2)
/usr/src/RPM/BUILD/fleet-commander-admin-0.15.1/tests/tools/ssh: line 2: /usr/src/tmp/fc-libvirt-test-system-0d4n8sjo/ssh-parms: No such file or directory
FAIL 04_libvirt_controller.py (exit status: 1)

+ exit 1
error: Bad exit status from /usr/src/tmp/rpm-tmp.48665 (%check)
```
